name: unet
seed: 3407
rgb: False

GOPRO:
  train: "Data/GOPRO/train"
  test: "Data/GOPRO/test"

REBlur:
  train: "Data/REBlur_rawevents/train"
  test: "Data/REBlur_rawevents/test"
  
train_setting:
  batch_size: 8
  num_workers: 0
  num_epoch: 101
  lr: 0.001

test_setting:
  batch_size: 1
  
num_bin: 7

unet:
  load_path: "Pretrained_Model/RE_Net_GRAY.pth" # GRAY
  # load_path: "Pretrained_Model/RE_Net_RGB.pth" # GRAY
  save_path: "Model/RE_Net_GRAY.pth" # GRAY
  # save_path: "Model/RE_Net_RGB.pth" # RGB
  load: False
